module.exports = {
  root: true,
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint'],
  rules: {
    camelcase: 'off',
    'no-mixed-operators': 'off',
    'no-await-in-loop': 'off',
    'no-continue': 'off',
    'no-use-before-define': 'off',
    'prefer-destructuring': 'off',
    'max-classes-per-file': 'off',
    'import/prefer-default-export': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-unresolved': 'off',
    'import/extensions': 'off',

    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-console': 'off',
    'func-names': 'off',
    'no-unused-vars': 'off',

    'global-require': 'off',
    'no-underscore-dangle': 'off',
    // 'no-plusplus': 'off',
    'no-unused-expressions': 'off',
    'no-param-reassign': 'off',
    'prefer-const': 'warn',
    'no-shadow': 'off',
    'no-bitwise': 'warn',
    'no-restricted-syntax': 'off',

    '@typescript-eslint/ban-types': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'error',
    '@typescript-eslint/no-explicit-any': 'warn',
  },
}
