module.exports = {
  root: true,
  env: {
    browser: true,
    es2021: true,
  },
  extends: ['airbnb-base', 'plugin:@typescript-eslint/recommended'],
  parserOptions: {
    ecmaVersion: 'latest',
    parser: '@typescript-eslint/parser',
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint'],
  rules: {
    camelcase: 'off',
    semi: ['error', 'never'],
    indent: ['error', 2],
    'no-mixed-operators': 'off',
    'no-await-in-loop': 'off',
    'no-continue': 'off',
    'guard-for-in': 'off',
    'max-len': 'off',
    'no-use-before-define': 'off',
    'prefer-destructuring': 'off',
    'max-classes-per-file': 'off',
    'import/prefer-default-export': 'off',
    '@typescript-eslint/ban-types': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    'import/no-extraneous-dependencies': 'off',
    'vue/multi-word-component-names': 'off',
    'generator-star-spacing': 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-console': 'off',
    'func-names': 'off',
    'no-unused-vars': 'warn',
    'import/no-unresolved': 'off',
    'import/extensions': 'off',
    'global-require': 'off',
    'no-underscore-dangle': 'off',
    'no-plusplus': 'off',
    'no-unused-expressions': 'off',
    'no-param-reassign': 'off',
    'prefer-const': 'warn',
    'no-shadow': 'off',
    'no-bitwise': 'off',
    'no-restricted-syntax': 'off',
  },
}
